language: c
compiler: gcc

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install gcc-4.4.7
- export CC="gcc-4.4.7"

script: "bash -c ./build.sh"